# Generated by Django 4.1.3 on 2023-04-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themeNAME', models.CharField(max_length=100)),
                ('themeAUTHOR', models.CharField(max_length=30)),
                ('themeSUPVISOR', models.CharField(max_length=30)),
                ('themeTYPE', models.CharField(max_length=10)),
                ('themeSUBJECT', models.CharField(max_length=20)),
                ('themeSTATUS', models.CharField(max_length=20)),
                ('themeDESCRIPT', models.CharField(max_length=2000)),
            ],
        ),
    ]
