# Generated by Django 4.2.1 on 2023-05-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='Class_of_tag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
