# Generated by Django 4.2.4 on 2023-08-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='Class_of_subject',
            new_name='class_of_subject',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='Class_of_tag',
            new_name='class_of_tag',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='Descript',
            new_name='descript',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='Type',
            new_name='type',
        ),
    ]
