# Generated by Django 4.1.7 on 2023-04-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme_Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('descript', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
