# Generated by Django 4.1.7 on 2023-04-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_theme_create_delete_theme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theme_Create',
            new_name='Theme',
        ),
    ]
