# Generated by Django 4.2a1 on 2023-08-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_remove_theme_subject_theme_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='theme',
            name='class_of_subject',
        ),
        migrations.AddField(
            model_name='theme',
            name='subject_color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
