# Generated by Django 4.1.3 on 2023-02-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.TextField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.TextField(max_length=15, null=True),
        ),
    ]
