# Generated by Django 4.1.7 on 2023-04-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivate',
            field=models.BooleanField(default=False),
        ),
    ]
