# Generated by Django 4.2.1 on 2023-08-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_view_window',
            field=models.BooleanField(default=False),
        ),
    ]
