# Generated by Django 4.1.3 on 2023-02-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.IntegerField(null=True),
        ),
    ]
