# Generated by Django 4.1.3 on 2023-08-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_user_is_view_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_Name',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.TextField(default='Нет', max_length=35),
        ),
    ]
