# Generated by Django 4.1.4 on 2023-01-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date_of_expiring',
            field=models.DurationField(null=True),
        ),
    ]
