# Generated by Django 4.1.7 on 2023-03-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_tag_announcement_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image_urls',
            field=models.TextField(blank=True),
        ),
    ]
