# Generated by Django 4.1.4 on 2023-01-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_of_expiring',
            field=models.DateTimeField(null=True),
        ),
    ]
