# Generated by Django 4.1.7 on 2023-03-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_announcement_image_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='image_urls',
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcement_images'),
        ),
    ]
