# Generated by Django 4.2.4 on 2023-09-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='announcement_id',
            field=models.IntegerField(null=True),
        ),
    ]
