# Generated by Django 4.1.7 on 2023-03-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
