# Generated by Django 4.1.7 on 2023-03-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_remove_announcement_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image_url',
            field=models.FilePathField(null=True, path='/static/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
