# Generated by Django 4.1.7 on 2023-03-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_announcement_image_url_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image_url',
            field=models.FilePathField(null=True, path='/static/img/announcement_images'),
        ),
    ]
