# Generated by Django 4.1.7 on 2023-03-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0010_alter_announcement_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image_url',
            field=models.FilePathField(null=True, path='static/img/announcements/covers'),
        ),
    ]
