# Generated by Django 4.1.7 on 2023-03-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='_subject',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
