# Generated by Django 4.2.3 on 2023-08-16 11:02

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="name",
            field=models.CharField(
                default=projects.models.get_file_name, max_length=100, null=True
            ),
        ),
    ]
