# Generated by Django 4.2.3 on 2023-08-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="_type",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
