# Generated by Django 4.2.3 on 2023-09-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_file_name_project__type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="_level",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
