# Generated by Django 3.2.17 on 2023-04-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='previous_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='projects.file'),
        ),
        migrations.AddField(
            model_name='file',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
