# Generated by Django 4.2.1 on 2023-08-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_expected_results_project_problem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='_subject',
        ),
        migrations.AddField(
            model_name='project',
            name='_subjects',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
