# Generated by Django 4.2.1 on 2023-08-15 18:28

from django.db import migrations, models
import projects.FileStorage
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project__type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='_tag',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, storage=projects.FileStorage.MyStorage, upload_to=projects.models.get_upload_path),
        ),
    ]
