# Generated by Django 4.2.3 on 2023-10-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project__level"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="defence_video",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
